sonar.projectKey=saleor-backend
sonar.projectName=Saleor Backend
sonar.projectVersion=3.24.0

sonar.sources=saleor
sonar.exclusions=\
  saleor/tests/**,\
  saleor/**/tests/**,\
  saleor/**/migrations/**,\
  saleor/static/**

sonar.tests=saleor/tests,saleor/**/tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

# Security rules
sonar.python.bandit.reportPaths=reports/bandit.json
